# The module to run Loki with. Supported values
# all, querier, table-manager, ingester, distributor
target: "all"

# Enables authentication through the X-Scope-OrgID header, which must be present
# if true. If false, the OrgID will always be set to "fake".
auth_enabled: false

# Configures the server of the launched module(s).
server:
  http_listen_port: 3100
  log_level: "info"

# Configures the ingester and how the ingester will register itself to a key value store.
ingester:
  wal:
    enabled: true
    dir: ${WAL_FOLDER:/loki/wal}
  lifecycler:
    ring:
      kvstore:
        store: "inmemory"
      replication_factor: 1
    # Duration to sleep before exiting to ensure metrics are scraped.
    # final_sleep: 5s
  chunk_retain_period: 30s
  max_chunk_age: 12h

# temporary configuration for loki:2.0.0
# for using boltdb-shipper-compactor
# ref: https://github.com/grafana/loki/issues/2815
compactor:
  working_directory: ${STORAGE_COMPACTOR_FOLDER:/loki/boltdb-shipper-compactor}
  shared_store: filesystem

# Configures the chunk index schema and where it is stored.
schema_config:
  configs:
    - from: 2018-04-15
      store: "boltdb"
      object_store: "filesystem"
      schema: "v11"
      index:
        prefix: "index_"
        period: 24h
      chunks:
        prefix: "chunk_"
        period: 24h
    - from: 2020-10-24
      store: "boltdb-shipper"
      object_store: "filesystem"
      schema: "v11"
      index:
        prefix: "index_"
        period: 24h
      chunks:
        prefix: "chunk_"
        period: 24h

# Configures where Loki will store data.
storage_config:
  # Configures storing index in BoltDB. Required fields only
  # required when boltdb is present in config.
  boltdb:
    # Location of BoltDB index files.
    directory: ${STORAGE_INDEX_FOLDER:/opt/loki/index}
  # Configures data shipping in BoltDB
  boltdb_shipper:
    active_index_directory: ${STORAGE_ACTIVE_INDEX_FOLDER:/tmp/loki/boltdb-shipper-active}
    cache_location: ${STORAGE_CACHE_FOLDER:/tmp/loki/boltdb-shipper-cache}
    cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  # Configures storing the chunks on the local filesystem. Required
  # fields only required when filesystem is present in config.
  filesystem:
    # Directory to store chunks in.
    directory: ${STORAGE_CHUNKS_FOLDER:/opt/loki/chunks}


# Configures limits per-tenant or globally
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 1h
  # Maximum number of log entries that will be returned for a query. 0 to disable.
  # [max_entries_limit: <int> | default = 5000 ]

# Configures how Loki will store data in the specific store.
chunk_store_config:
  max_look_back_period: 0s

# Configures the table manager for retention
table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: true
  retention_period: 720h
