server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ${POSITIONS_FILEPATH:/tmp/positions.yaml}

clients:
  - url: ${LOKI_CLIENT_URL:"http://userver-loki:3100/loki/api/v1/push"}

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: ${LOG_FILES_SELECTOR:/logs/*.log}
